### ISSUE TITLE
Visualisation Of Storage Space

### ISSUE THREAD

**Issue by borhara** [SHIV5T3R/File-Manager#2]
# Outcome
The outcome of these tasks is to allow the user to see their storage space.

**Comment by swordensen** [comment]
I am going to be working on this next! But, if other people are already working on it please let me know.

and feel free to assign the issue to me.

**Comment by swordensen** [comment]
Just wanted to give an update on this issue. 

Android does not allow access to the root directory on the device. As a result it is a tad difficult to figure out what to display at the root level. 

I figure we want to display something like this: 

![image](https://github.com/SHIV5T3R/Maestro/assets/21202515/a2c9e928-0ed4-43d6-b6b9-3fec925f93e8)


Unfortunately, the path to those locations are hidden. 

But, expo-file-system has a method called: ` StorageAccessFramework.getUriForDirectoryInRoot` 

Unfortunately, when I try to use it like so ` StorageAccessFramework.getUriForDirectoryInRoot("alarms");`

it returns `content://com.android.externalstorage.documents/tree/primary:alarms/document/primary:alarms` instead of `content://com.android.externalstorage.documents/tree/primary%3AAlarms` which is the correct path I guess. 

not sure how we're going to go about solving that but I figured I'd give yall an update.

**Comment by swordensen** [comment]
and you can check out my progress here: https://github.com/swordensen/Maestro/tree/feature/storageVisualization

**Comment by swordensen** [comment]
https://support.google.com/googleplay/android-developer/answer/10467955?hl=en

So it turns out we need to ask the user for permission to access outside directories. 

I'll try to add this.
